# Site settings
title: Lilly Chin
description: Lilly Chin's personal website ( lillych.in ), student at MIT (Massachusetts Institute of Technology) interested in electrical engineering, computer science, mechanical engineering and biomedical engineering
url: "lillych.in" # the base hostname & protocol for your site
github_username: ltchin
markdown: kramdown