# Site settings
title: Tyler King
description: Tyler King's website
url: "tylertking.com" # the base hostname & protocol for your site
github_username: tylertking
markdown: kramdown
theme: jekyll-theme-minimal